name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Copy icon file
        run: |
          mkdir icons
          copy src\main\resources\ua\dscorp\poessence\icons\Regal_Orb.ico icons\

      - name: Package with jpackage
        run: jpackage --input target --name PoEssence --main-jar PoEssence-1.0.jar --main-class ua.dscorp.poessence.GUIStarter --type exe --dest target --app-version 1.0 --icon icons\Regal_Orb.ico --win-dir-chooser --win-menu --win-menu-group PoEssence --win-shortcut --win-shortcut-prompt --win-shortcut-script runAsAdmin.bat

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: poessence-jar
          path: target/PoEssence-1.0.jar

      - name: Upload EXE Installer
        uses: actions/upload-artifact@v4
        with:
          name: poessence-installer
          path: target/PoEssence-1.0.exe
