name: Create Release

on:
  #workflow_dispatch: # Allows you to manually trigger this workflow
  # Uncomment the following lines if you want it to trigger automatically on new tags
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch the latest tag
        id: fetch-tag
        run: |
          # Fetch all tags from the remote
          git fetch --tags
          
          # Get the latest tag matching the pattern v*.*.*
          latest_tag=$(git tag -l 'v*' | sort -V | tail -n 1)
          
          # Output the tag
          echo "Latest tag: $latest_tag"
          echo "RELEASE_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Download ZIP artifacts from the previous build
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          name: poessence-jar
          path: ./artifacts

      - name: Download second ZIP artifact from the previous build
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          name: poessence-installer
          path: ./artifacts

      - name: Rename
        run: mv ./artifacts/PoEssence-1.0.jar ./artifacts/PoEssence.jar

      - name: Rename 2
        run: mv ./artifacts/PoEssence-1.0.exe ./artifacts/PoEssence.exe


      - name: upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
            tag: ${{ env.RELEASE_TAG }}
            files: ./artifacts/PoEssence.jar
